function generateName(name) {
                const autoGenerate = name.emitNode.autoGenerate;
                if ((autoGenerate.flags & 7 /* KindMask */) === 4 /* Node */) {
                    return generateNameCached(getNodeForGeneratedName(name), isPrivateIdentifier(name), autoGenerate.flags, autoGenerate.prefix, autoGenerate.suffix);
                }
                else {
                    const autoGenerateId = autoGenerate.id;
                    return autoGeneratedIdToGeneratedName[autoGenerateId] || (autoGeneratedIdToGeneratedName[autoGenerateId] = makeName(name));
                }
            }