function HostCapabilities(EXTENDED_PANEL_MENU, EXTENDED_PANEL_ICONS, DELEGATE_APE_ENGINE, SUPPORT_HTML_EXTENSIONS, DISABLE_FLASH_EXTENSIONS) {
	this.EXTENDED_PANEL_MENU = EXTENDED_PANEL_MENU;
	this.EXTENDED_PANEL_ICONS = EXTENDED_PANEL_ICONS;
	this.DELEGATE_APE_ENGINE = DELEGATE_APE_ENGINE;
	this.SUPPORT_HTML_EXTENSIONS = SUPPORT_HTML_EXTENSIONS;
	this.DISABLE_FLASH_EXTENSIONS = DISABLE_FLASH_EXTENSIONS; // Since 5.0.0
}