function JIe(e){return new Promise(t=>{process.nextTick(()=>{let r={manufacturer:"",model:"Computer",version:"",serial:"-",uuid:"-",sku:"-"};if((C3||T3||A3||I3)&&Dp("export LC_ALL=C; dmidecode -t system 2>/dev/null; unset LC_ALL",function(i,a){let n=a.toString().split(`
`);r.manufacturer=ze.getValue(n,"manufacturer"),r.model=ze.getValue(n,"product name"),r.version=ze.getValue(n,"version"),r.serial=ze.getValue(n,"serial number"),r.uuid=ze.getValue(n,"uuid"),r.sku=ze.getValue(n,"sku number");let s=`echo -n "product_name: "; cat /sys/devices/virtual/dmi/id/product_name 2>/dev/null; echo;
            echo -n "product_serial: "; cat /sys/devices/virtual/dmi/id/product_serial 2>/dev/null; echo;
            echo -n "product_uuid: "; cat /sys/devices/virtual/dmi/id/product_uuid 2>/dev/null; echo;
            echo -n "product_version: "; cat /sys/devices/virtual/dmi/id/product_version 2>/dev/null; echo;
            echo -n "sys_vendor: "; cat /sys/devices/virtual/dmi/id/sys_vendor 2>/dev/null; echo;`;try{n=J_(s).toString().split(`
`),r.manufacturer=r.manufacturer===""?ze.getValue(n,"sys_vendor"):r.manufacturer,r.model=r.model===""?ze.getValue(n,"product_name"):r.model,r.version=r.version===""?ze.getValue(n,"product_version"):r.version,r.serial=r.serial===""?ze.getValue(n,"product_serial"):r.serial,r.uuid=r.uuid===""?ze.getValue(n,"product_uuid"):r.uuid}catch{ze.noop()}(!r.serial||r.serial.toLowerCase().indexOf("o.e.m.")!==-1)&&(r.serial="-"),(!r.manufacturer||r.manufacturer.toLowerCase().indexOf("o.e.m.")!==-1)&&(r.manufacturer=""),(!r.model||r.model.toLowerCase().indexOf("o.e.m.")!==-1)&&(r.model="Computer"),(!r.version||r.version.toLowerCase().indexOf("o.e.m.")!==-1)&&(r.version=""),(!r.sku||r.sku.toLowerCase().indexOf("o.e.m.")!==-1)&&(r.sku="-"),(Z_.existsSync("/.dockerenv")||Z_.existsSync("/.dockerinit"))&&(r.model="Docker Container"),r.manufacturer===""&&r.model==="Computer"&&r.version===""?Dp('dmesg | grep -i virtual | grep -iE "vmware|qemu|kvm|xen"',function(o,u){o||u.toString().split(`
`).length>0&&(r.model="Virtual machine"),r.manufacturer===""&&r.model==="Computer"&&r.version===""?Z_.readFile("/proc/cpuinfo",function(l,p){if(!l){let c=p.toString().split(`
`);r.model=ze.getValue(c,"hardware",":",!0).toUpperCase(),r.version=ze.getValue(c,"revision",":",!0).toLowerCase(),r.serial=ze.getValue(c,"serial",":",!0),(r.model==="BCM2835"||r.model==="BCM2708"||r.model==="BCM2709"||r.model==="BCM2835"||r.model==="BCM2837")&&(["c03112"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi 4 Model B",r.version=r.version+" - Rev. 1.2"),["a03111","b03111","c03111"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi 4 Model B",r.version=r.version+" - Rev. 1.1"),["a02082","a22082","a32082"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi 3 Model B",r.version=r.version+" - Rev. 1.2"),["a020d3"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi 3 Model B+",r.version=r.version+" - Rev. 1.3"),["9020e0"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi 3 Model A+",r.version=r.version+" - Rev. 1.3"),["a01040"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi 2 Model B",r.version=r.version+" - Rev. 1.0"),["a01041","a21041"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi 2 Model B",r.version=r.version+" - Rev. 1.1"),["a22042"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi 2 Model B",r.version=r.version+" - Rev. 1.2"),["900092"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi Zero",r.version=r.version+" - Rev 1.2"),["900093","920093"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi Zero",r.version=r.version+" - Rev 1.3"),["9000c1"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi Zero W",r.version=r.version+" - Rev 1.1"),["0002","0003"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi Model B",r.version=r.version+" - Rev 1.0"),["0004","0005","0006","000d","000e","000f"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi Model B",r.version=r.version+" - Rev 2.0"),["0007","0008","0009"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi Model A",r.version=r.version+" - Rev 2.0"),["0010"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi Model B+",r.version=r.version+" - Rev 1.0"),["0012"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi Model A+",r.version=r.version+" - Rev 1.0"),["0013"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi Model B+",r.version=r.version+" - Rev 1.2"),["0015"].indexOf(r.version)>=0&&(r.model=r.model+" - Pi Model A+",r.version=r.version+" - Rev 1.1"),r.model.indexOf("Pi")!==-1&&r.version&&(r.manufacturer="Raspberry Pi Foundation"))}e&&e(r),t(r)}):(e&&e(r),t(r))}):(e&&e(r),t(r))}),D3&&Dp("ioreg -c IOPlatformExpertDevice -d 2",function(i,a){if(!i){let n=a.toString().replace(/[<>"]/g,"").split(`
`);r.manufacturer=ze.getValue(n,"manufacturer","=",!0),r.model=ze.getValue(n,"model","=",!0),r.version=ze.getValue(n,"version","=",!0),r.serial=ze.getValue(n,"ioplatformserialnumber","=",!0),r.uuid=ze.getValue(n,"ioplatformuuid","=",!0),r.sku=ze.getValue(n,"board-id","=",!0)}e&&e(r),t(r)}),P3&&(e&&e(r),t(r)),k3)try{ze.wmic("csproduct get /value").then((i,a)=>{if(a)e&&e(r),t(r);else{let n=i.split(`\r
`);r.manufacturer=ze.getValue(n,"vendor","="),r.model=ze.getValue(n,"name","="),r.version=ze.getValue(n,"version","="),r.serial=ze.getValue(n,"identifyingnumber","="),r.uuid=ze.getValue(n,"uuid","="),ze.wmic("/namespace:\\\\root\\wmi path MS_SystemInformation get /value").then((s,o)=>{if(!o){let u=s.split(`\r
`);r.sku=ze.getValue(u,"systemsku","=")}e&&e(r),t(r)})}})}catch{e&&e(r),t(r)}})})}