async function makeFcUtilsFunctionTmpDomainToken(token) {

  const tmpServiceName = 'fc-domain-challenge';

  await makeService({
    serviceName: tmpServiceName,
    description: 'generated by Funcraft for authentication',
    vpcConfig: {},
    nasConfig: {}
  });

  const functionCode = await getFcUtilsFunctionCode('tmp-domain-token.js');

  const tmpFunctionName = `fc-${token}`;

  const codes = {
    'index.js': functionCode
  };

  await makeFcUtilsFunction({
    serviceName: tmpServiceName,
    functionName: tmpFunctionName,
    codes,
    description: 'used for tmp domain service to authenticate.',
    handler: 'index.handler'
  });

  const tmpTriggerName = 'tmp-domain-http';

  const triggerProperties = {
    'AuthType': 'ANONYMOUS',
    'Methods': [
      'GET',
      'POST',
      'PUT'
    ]
  };

  await makeTrigger({
    serviceName: tmpServiceName,
    functionName: tmpFunctionName,
    triggerName: tmpTriggerName,
    triggerType: 'HTTP',
    triggerProperties
  });

  return {
    tmpServiceName,
    tmpFunctionName,
    tmpTriggerName
  };
}