function matchInstanceEnv(tt, env, expectedEnv) {
  // PORT is generated by service manager
  // STRONGLOOP_LICENSE is specifically inherited from PM environment
  tt.assert(env.PORT, 'PORT is set');
  tt.equal(env.STRONGLOOP_LICENSE, 'inherited',
           'STRONGLOOP_LICENSE is inherited from PM environment');
  tt.equal(env.STRONGLOOP_TRACES_ID, '1', 'STRONGLOOP_TRACES_ID set by PM');
  var appEnv = _.omit(env, 'PORT', 'STRONGLOOP_LICENSE',
                      'STRONGLOOP_TRACES_ID');
  tt.deepEqual(appEnv, expectedEnv, 'generated instance environment matches');
}