function oPe(e,t){let r={kernel:vg.release(),openssl:"",systemOpenssl:"",systemOpensslLib:"",node:process.versions.node,v8:process.versions.v8,npm:"",yarn:"",pm2:"",gulp:"",grunt:"",git:"",tsc:"",mysql:"",redis:"",mongodb:"",apache:"",nginx:"",php:"",docker:"",postfix:"",postgresql:"",perl:"",python:"",python3:"",pip:"",pip3:"",java:"",gcc:"",virtualbox:"",dotnet:""};function i(a){if(a==="*")return{versions:r,counter:26};if(!Array.isArray(a)){a=a.trim().toLowerCase().replace(/,+/g,"|").replace(/ /g,"|"),a=a.split("|");let n={versions:{},counter:0};return a.forEach(s=>{if(s)for(let o in r)({}).hasOwnProperty.call(r,o)&&o.toLowerCase()===s.toLowerCase()&&!{}.hasOwnProperty.call(n.versions,o)&&(n.versions[o]=r[o],o==="openssl"&&(n.versions.systemOpenssl="",n.versions.systemOpensslLib=""),n.versions[o]||n.counter++)}),n}}return new Promise(a=>{process.nextTick(()=>{Mr.isFunction(e)&&!t?(t=e,e="*"):e=e||"*";let n=i(e),s=n.counter,o=function(){return function(){--s==0&&(t&&t(n.versions),a(n.versions))}}();try{if({}.hasOwnProperty.call(n.versions,"openssl")&&(n.versions.openssl=process.versions.openssl,Ht("openssl version",function(u,l){if(!u){let c=l.toString().split(`
`)[0].trim().split(" ");n.versions.systemOpenssl=c.length>0?c[1]:c[0],n.versions.systemOpensslLib=c.length>0?c[0]:"openssl"}o()})),{}.hasOwnProperty.call(n.versions,"npm")&&Ht("npm -v",function(u,l){u||(n.versions.npm=l.toString().split(`
`)[0]),o()}),{}.hasOwnProperty.call(n.versions,"pm2")&&Ht("pm2 -v",function(u,l){if(!u){let p=l.toString().split(`
`)[0].trim();p.startsWith("[PM2]")||(n.versions.pm2=p)}o()}),{}.hasOwnProperty.call(n.versions,"yarn")&&Ht("yarn --version",function(u,l){u||(n.versions.yarn=l.toString().split(`
`)[0]),o()}),{}.hasOwnProperty.call(n.versions,"gulp")&&Ht("gulp --version",function(u,l){if(!u){let p=l.toString().split(`
`)[0]||"";n.versions.gulp=(p.toLowerCase().split("version")[1]||"").trim()}o()}),{}.hasOwnProperty.call(n.versions,"tsc")&&Ht("tsc --version",function(u,l){if(!u){let p=l.toString().split(`
`)[0]||"";n.versions.tsc=(p.toLowerCase().split("version")[1]||"").trim()}o()}),{}.hasOwnProperty.call(n.versions,"grunt")&&Ht("grunt --version",function(u,l){if(!u){let p=l.toString().split(`
`)[0]||"";n.versions.grunt=(p.toLowerCase().split("cli v")[1]||"").trim()}o()}),{}.hasOwnProperty.call(n.versions,"git"))if(Y1){let u=Nte.existsSync("/usr/local/Cellar/git");Mr.darwinXcodeExists()||u?Ht("git --version",function(l,p){if(!l){let c=p.toString().split(`
`)[0]||"";c=(c.toLowerCase().split("version")[1]||"").trim(),n.versions.git=(c.split(" ")[0]||"").trim()}o()}):o()}else Ht("git --version",function(u,l){if(!u){let p=l.toString().split(`
`)[0]||"";p=(p.toLowerCase().split("version")[1]||"").trim(),n.versions.git=(p.split(" ")[0]||"").trim()}o()});({}).hasOwnProperty.call(n.versions,"apache")&&Ht("apachectl -v 2>&1",function(u,l){if(!u){let p=(l.toString().split(`
`)[0]||"").split(":");n.versions.apache=p.length>1?p[1].replace("Apache","").replace("/","").trim():""}o()}),{}.hasOwnProperty.call(n.versions,"nginx")&&Ht("nginx -v 2>&1",function(u,l){if(!u){let p=l.toString().split(`
`)[0]||"";n.versions.nginx=(p.toLowerCase().split("/")[1]||"").trim()}o()}),{}.hasOwnProperty.call(n.versions,"mysql")&&Ht("mysql -V",function(u,l){if(!u){let p=l.toString().split(`
`)[0]||"";if(p=p.toLowerCase(),p.indexOf(",")>-1){p=(p.split(",")[0]||"").trim();let c=p.split(" ");n.versions.mysql=(c[c.length-1]||"").trim()}else p.indexOf(" ver ")>-1&&(p=p.split(" ver ")[1],n.versions.mysql=p.split(" ")[0])}o()}),{}.hasOwnProperty.call(n.versions,"php")&&Ht("php -v",function(u,l){if(!u){let c=(l.toString().split(`
`)[0]||"").split("(");c[0].indexOf("-")&&(c=c[0].split("-")),n.versions.php=c[0].replace(/[^0-9.]/g,"")}o()}),{}.hasOwnProperty.call(n.versions,"redis")&&Ht("redis-server --version",function(u,l){if(!u){let c=(l.toString().split(`
`)[0]||"").split(" ");n.versions.redis=Mr.getValue(c,"v","=",!0)}o()}),{}.hasOwnProperty.call(n.versions,"docker")&&Ht("docker --version",function(u,l){if(!u){let c=(l.toString().split(`
`)[0]||"").split(" ");n.versions.docker=c.length>2&&c[2].endsWith(",")?c[2].slice(0,-1):""}o()}),{}.hasOwnProperty.call(n.versions,"postfix")&&Ht("postconf -d | grep mail_version",function(u,l){if(!u){let p=l.toString().split(`
`)||[];n.versions.postfix=Mr.getValue(p,"mail_version","=",!0)}o()}),{}.hasOwnProperty.call(n.versions,"mongodb")&&Ht("mongod --version",function(u,l){if(!u){let p=l.toString().split(`
`)[0]||"";n.versions.mongodb=(p.toLowerCase().split(",")[0]||"").replace(/[^0-9.]/g,"")}o()}),{}.hasOwnProperty.call(n.versions,"postgresql")&&(O3?Ht("locate bin/postgres",function(u,l){if(u)Ht("psql -V",function(p,c){if(!p){let d=c.toString().split(`
`)[0].split(" ")||[];n.versions.postgresql=d.length?d[d.length-1]:"",n.versions.postgresql=n.versions.postgresql.split("-")[0]}o()}),o();else{let p=l.toString().split(`
`).sort();p.length?Ht(p[p.length-1]+" -V",function(c,d){if(!c){let f=d.toString().split(`
`)[0].split(" ")||[];n.versions.postgresql=f.length?f[f.length-1]:""}o()}):o()}}):yg?Mr.wmic("service get /value").then(u=>{let l=u.split(/\n\s*\n/);for(let p=0;p<l.length;p++)if(l[p].trim()!==""){let c=l[p].trim().split(`\r
`),d=Mr.getValue(c,"caption","=",!0).toLowerCase();if(d.indexOf("postgresql")>-1){let f=d.split(" server ");f.length>1&&(n.versions.postgresql=f[1])}}o()}):Ht("postgres -V",function(u,l){if(!u){let p=l.toString().split(`
`)[0].split(" ")||[];n.versions.postgresql=p.length?p[p.length-1]:""}o()})),{}.hasOwnProperty.call(n.versions,"perl")&&Ht("perl -v",function(u,l){if(!u){let p=l.toString().split(`
`)||"";for(;p.length>0&&p[0].trim()==="";)p.shift();p.length>0&&(n.versions.perl=p[0].split("(").pop().split(")")[0].replace("v",""))}o()}),{}.hasOwnProperty.call(n.versions,"python")&&Ht("python -V 2>&1",function(u,l){if(!u){let p=l.toString().split(`
`)[0]||"";n.versions.python=p.toLowerCase().replace("python","").trim()}o()}),{}.hasOwnProperty.call(n.versions,"python3")&&Ht("python3 -V 2>&1",function(u,l){if(!u){let p=l.toString().split(`
`)[0]||"";n.versions.python3=p.toLowerCase().replace("python","").trim()}o()}),{}.hasOwnProperty.call(n.versions,"pip")&&Ht("pip -V 2>&1",function(u,l){if(!u){let c=(l.toString().split(`
`)[0]||"").split(" ");n.versions.pip=c.length>=2?c[1]:""}o()}),{}.hasOwnProperty.call(n.versions,"pip3")&&Ht("pip3 -V 2>&1",function(u,l){if(!u){let c=(l.toString().split(`
`)[0]||"").split(" ");n.versions.pip3=c.length>=2?c[1]:""}o()}),{}.hasOwnProperty.call(n.versions,"java")&&(Y1?Ht("/usr/libexec/java_home -V 2>&1",function(u,l){!u&&l.toString().toLowerCase().indexOf("no java runtime")===-1?Ht("java -version 2>&1",function(p,c){if(!p){let f=(c.toString().split(`
`)[0]||"").split('"');n.versions.java=f.length===3?f[1].trim():""}o()}):o()}):Ht("java -version 2>&1",function(u,l){if(!u){let c=(l.toString().split(`
`)[0]||"").split('"');n.versions.java=c.length===3?c[1].trim():""}o()})),{}.hasOwnProperty.call(n.versions,"gcc")&&(Y1&&Mr.darwinXcodeExists()||!Y1?Ht("gcc -dumpversion",function(u,l){u||(n.versions.gcc=l.toString().split(`
`)[0].trim()||""),n.versions.gcc.indexOf(".")>-1?o():Ht("gcc --version",function(p,c){if(!p){let d=c.toString().split(`
`)[0].trim();if(d.indexOf("gcc")>-1&&d.indexOf(")")>-1){let f=d.split(")");n.versions.gcc=f[1].trim()||n.versions.gcc}}o()})}):o()),{}.hasOwnProperty.call(n.versions,"virtualbox")&&Ht(Mr.getVboxmanage()+" -v 2>&1",function(u,l){if(!u){let c=(l.toString().split(`
`)[0]||"").split("r");n.versions.virtualbox=c[0]}o()}),{}.hasOwnProperty.call(n.versions,"dotnet")&&Ht("dotnet --version 2>&1",function(u,l){if(!u){let p=l.toString().split(`
`)[0]||"";n.versions.dotnet=p.trim()}o()})}catch{t&&t(n.versions),a(n.versions)}})})}