function reset2() {
                nodeIdToGeneratedName = [];
                nodeIdToGeneratedPrivateName = [];
                autoGeneratedIdToGeneratedName = [];
                generatedNames = /* @__PURE__ */ new Set();
                formattedNameTempFlagsStack = [];
                formattedNameTempFlags = /* @__PURE__ */ new Map();
                privateNameTempFlagsStack = [];
                privateNameTempFlags = 0 /* Auto */;
                tempFlagsStack = [];
                tempFlags = 0 /* Auto */;
                reservedNamesStack = [];
                reservedNames = void 0;
                reservedPrivateNamesStack = [];
                reservedPrivateNames = void 0;
                currentSourceFile = void 0;
                currentLineMap = void 0;
                detachedCommentsInfo = void 0;
                setWriter(
                /*output*/
                void 0, 
                /*_sourceMapGenerator*/
                void 0);
            }