function Sanitizer() {
    _classCallCheck(this, Sanitizer);
    this._options = {
      // HTML tags that are allowed to be used. Tags were extracted from Google Caja
      allowedTags: ['a', 'abbr', 'acronym', 'address', 'area', 'article', 'aside', 'audio', 'b', 'bdi', 'bdo', 'big', 'blockquote', 'br', 'button', 'canvas', 'caption', 'center', 'cite', 'code', 'col', 'colgroup', 'colspan', 'command', 'data', 'datalist', 'dd', 'del', 'details', 'dfn', 'dir', 'div', 'dl', 'dt', 'em', 'fieldset', 'figcaption', 'figure', 'font', 'footer', 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'header', 'hgroup', 'hr', 'i',
      // 'iframe' is allowed by Google Caja, but disallowed by default by sanitize-html
      // , 'iframe'
      'img', 'input', 'ins', 'kbd', 'label', 'legend', 'li', 'map', 'mark', 'menu', 'meter', 'nav', 'nobr', 'ol', 'optgroup', 'option', 'output', 'p', 'pre', 'progress', 'q', 'rowspan', 's', 'samp', 'section', 'select', 'small', 'source', 'span', 'strike', 'strong', 'sub', 'summary', 'sup', 'table', 'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'time', 'tr', 'track', 'tt', 'u', 'ul', 'var', 'video', 'wbr'],
      // Attributes that HTML tags are allowed to have, extracted from Google Caja.
      // See https://github.com/jupyterlab/jupyterlab/issues/1812#issuecomment-285848435
      allowedAttributes: {
        '*': ['class', 'dir', 'draggable', 'hidden', 'id', 'inert', 'itemprop', 'itemref', 'itemscope', 'lang', 'spellcheck', 'style', 'title', 'translate'],
        // 'rel' and 'target' were *not* allowed by Google Caja
        a: ['accesskey', 'coords', 'href', 'hreflang', 'name', 'rel', 'shape', 'tabindex', 'target', 'type'],
        area: ['accesskey', 'alt', 'coords', 'href', 'nohref', 'shape', 'tabindex'],
        // 'autoplay' was *not* allowed by Google Caja
        audio: ['autoplay', 'controls', 'loop', 'mediagroup', 'muted', 'preload', 'src'],
        bdo: ['dir'],
        blockquote: ['cite'],
        br: ['clear'],
        button: ['accesskey', 'data-commandlinker-args', 'data-commandlinker-command', 'disabled', 'name', 'tabindex', 'type', 'value'],
        canvas: ['height', 'width'],
        caption: ['align'],
        col: ['align', 'char', 'charoff', 'span', 'valign', 'width'],
        colgroup: ['align', 'char', 'charoff', 'span', 'valign', 'width'],
        command: ['checked', 'command', 'disabled', 'icon', 'label', 'radiogroup', 'type'],
        data: ['value'],
        del: ['cite', 'datetime'],
        details: ['open'],
        dir: ['compact'],
        div: ['align'],
        dl: ['compact'],
        fieldset: ['disabled'],
        font: ['color', 'face', 'size'],
        form: ['accept', 'autocomplete', 'enctype', 'method', 'name', 'novalidate'],
        h1: ['align'],
        h2: ['align'],
        h3: ['align'],
        h4: ['align'],
        h5: ['align'],
        h6: ['align'],
        hr: ['align', 'noshade', 'size', 'width'],
        iframe: ['align', 'frameborder', 'height', 'marginheight', 'marginwidth', 'width'],
        img: ['align', 'alt', 'border', 'height', 'hspace', 'ismap', 'name', 'src', 'usemap', 'vspace', 'width'],
        input: ['accept', 'accesskey', 'align', 'alt', 'autocomplete', 'checked', 'disabled', 'inputmode', 'ismap', 'list', 'max', 'maxlength', 'min', 'multiple', 'name', 'placeholder', 'readonly', 'required', 'size', 'src', 'step', 'tabindex', 'type', 'usemap', 'value'],
        ins: ['cite', 'datetime'],
        label: ['accesskey', 'for'],
        legend: ['accesskey', 'align'],
        li: ['type', 'value'],
        map: ['name'],
        menu: ['compact', 'label', 'type'],
        meter: ['high', 'low', 'max', 'min', 'value'],
        ol: ['compact', 'reversed', 'start', 'type'],
        optgroup: ['disabled', 'label'],
        option: ['disabled', 'label', 'selected', 'value'],
        output: ['for', 'name'],
        p: ['align'],
        pre: ['width'],
        progress: ['max', 'min', 'value'],
        q: ['cite'],
        select: ['autocomplete', 'disabled', 'multiple', 'name', 'required', 'size', 'tabindex'],
        source: ['type'],
        table: ['align', 'bgcolor', 'border', 'cellpadding', 'cellspacing', 'frame', 'rules', 'summary', 'width'],
        tbody: ['align', 'char', 'charoff', 'valign'],
        td: ['abbr', 'align', 'axis', 'bgcolor', 'char', 'charoff', 'colspan', 'headers', 'height', 'nowrap', 'rowspan', 'scope', 'valign', 'width'],
        textarea: ['accesskey', 'autocomplete', 'cols', 'disabled', 'inputmode', 'name', 'placeholder', 'readonly', 'required', 'rows', 'tabindex', 'wrap'],
        tfoot: ['align', 'char', 'charoff', 'valign'],
        th: ['abbr', 'align', 'axis', 'bgcolor', 'char', 'charoff', 'colspan', 'headers', 'height', 'nowrap', 'rowspan', 'scope', 'valign', 'width'],
        thead: ['align', 'char', 'charoff', 'valign'],
        tr: ['align', 'bgcolor', 'char', 'charoff', 'valign'],
        track: ['default', 'kind', 'label', 'srclang'],
        ul: ['compact', 'type'],
        video: ['autoplay', 'controls', 'height', 'loop', 'mediagroup', 'muted', 'poster', 'preload', 'src', 'width']
      },
      // Inline CSS styles that HTML tags may have (and their allowed values)
      allowedStyles: {
        // To simplify the data, all styles are allowed on all tags that allow the style attribute
        '*': {
          'backface-visibility': [CssProp.BACKFACE_VISIBILITY],
          background: [CssProp.BACKGROUND],
          'background-attachment': [CssProp.BACKGROUND_ATTACHMENT],
          'background-clip': [CssProp.BACKGROUND_CLIP],
          'background-color': [CssProp.BACKGROUND_COLOR],
          'background-image': [CssProp.BACKGROUND_IMAGE],
          'background-origin': [CssProp.BACKGROUND_ORIGIN],
          'background-position': [CssProp.BACKGROUND_POSITION],
          'background-repeat': [CssProp.BACKGROUND_REPEAT],
          'background-size': [CssProp.BACKGROUND_SIZE],
          border: [CssProp.BORDER],
          'border-bottom': [CssProp.BORDER_BOTTOM],
          'border-bottom-color': [CssProp.BORDER_BOTTOM_COLOR],
          'border-bottom-left-radius': [CssProp.BORDER_BOTTOM_LEFT_RADIUS],
          'border-bottom-right-radius': [CssProp.BORDER_BOTTOM_RIGHT_RADIUS],
          'border-bottom-style': [CssProp.BORDER_BOTTOM_STYLE],
          'border-bottom-width': [CssProp.BORDER_BOTTOM_WIDTH],
          'border-collapse': [CssProp.BORDER_COLLAPSE],
          'border-color': [CssProp.BORDER_COLOR],
          'border-left': [CssProp.BORDER_LEFT],
          'border-left-color': [CssProp.BORDER_LEFT_COLOR],
          'border-left-style': [CssProp.BORDER_LEFT_STYLE],
          'border-left-width': [CssProp.BORDER_LEFT_WIDTH],
          'border-radius': [CssProp.BORDER_RADIUS],
          'border-right': [CssProp.BORDER_RIGHT],
          'border-right-color': [CssProp.BORDER_RIGHT_COLOR],
          'border-right-style': [CssProp.BORDER_RIGHT_STYLE],
          'border-right-width': [CssProp.BORDER_RIGHT_WIDTH],
          'border-spacing': [CssProp.BORDER_SPACING],
          'border-style': [CssProp.BORDER_STYLE],
          'border-top': [CssProp.BORDER_TOP],
          'border-top-color': [CssProp.BORDER_TOP_COLOR],
          'border-top-left-radius': [CssProp.BORDER_TOP_LEFT_RADIUS],
          'border-top-right-radius': [CssProp.BORDER_TOP_RIGHT_RADIUS],
          'border-top-style': [CssProp.BORDER_TOP_STYLE],
          'border-top-width': [CssProp.BORDER_TOP_WIDTH],
          'border-width': [CssProp.BORDER_WIDTH],
          bottom: [CssProp.BOTTOM],
          box: [CssProp.BOX],
          'box-shadow': [CssProp.BOX_SHADOW],
          'box-sizing': [CssProp.BOX_SIZING],
          'caption-side': [CssProp.CAPTION_SIDE],
          clear: [CssProp.CLEAR],
          clip: [CssProp.CLIP],
          color: [CssProp.COLOR],
          cursor: [CssProp.CURSOR],
          direction: [CssProp.DIRECTION],
          display: [CssProp.DISPLAY],
          'display-inside': [CssProp.DISPLAY_INSIDE],
          'display-outside': [CssProp.DISPLAY_OUTSIDE],
          elevation: [CssProp.ELEVATION],
          'empty-cells': [CssProp.EMPTY_CELLS],
          "float": [CssProp.FLOAT],
          font: [CssProp.FONT],
          'font-family': [CssProp.FONT_FAMILY],
          'font-size': [CssProp.FONT_SIZE],
          'font-stretch': [CssProp.FONT_STRETCH],
          'font-style': [CssProp.FONT_STYLE],
          'font-variant': [CssProp.FONT_VARIANT],
          'font-weight': [CssProp.FONT_WEIGHT],
          height: [CssProp.HEIGHT],
          left: [CssProp.LEFT],
          'letter-spacing': [CssProp.LETTER_SPACING],
          'line-height': [CssProp.LINE_HEIGHT],
          'list-style': [CssProp.LIST_STYLE],
          'list-style-image': [CssProp.LIST_STYLE_IMAGE],
          'list-style-position': [CssProp.LIST_STYLE_POSITION],
          'list-style-type': [CssProp.LIST_STYLE_TYPE],
          margin: [CssProp.MARGIN],
          'margin-bottom': [CssProp.MARGIN_BOTTOM],
          'margin-left': [CssProp.MARGIN_LEFT],
          'margin-right': [CssProp.MARGIN_RIGHT],
          'margin-top': [CssProp.MARGIN_TOP],
          'max-height': [CssProp.MAX_HEIGHT],
          'max-width': [CssProp.MAX_WIDTH],
          'min-height': [CssProp.MIN_HEIGHT],
          'min-width': [CssProp.MIN_WIDTH],
          opacity: [CssProp.OPACITY],
          outline: [CssProp.OUTLINE],
          'outline-color': [CssProp.OUTLINE_COLOR],
          'outline-style': [CssProp.OUTLINE_STYLE],
          'outline-width': [CssProp.OUTLINE_WIDTH],
          overflow: [CssProp.OVERFLOW],
          'overflow-wrap': [CssProp.OVERFLOW_WRAP],
          'overflow-x': [CssProp.OVERFLOW_X],
          'overflow-y': [CssProp.OVERFLOW_Y],
          padding: [CssProp.PADDING],
          'padding-bottom': [CssProp.PADDING_BOTTOM],
          'padding-left': [CssProp.PADDING_LEFT],
          'padding-right': [CssProp.PADDING_RIGHT],
          'padding-top': [CssProp.PADDING_TOP],
          'page-break-after': [CssProp.PAGE_BREAK_AFTER],
          'page-break-before': [CssProp.PAGE_BREAK_BEFORE],
          'page-break-inside': [CssProp.PAGE_BREAK_INSIDE],
          'pause-after': [CssProp.PAUSE_AFTER],
          perspective: [CssProp.PERSPECTIVE],
          pitch: [CssProp.PITCH],
          'pitch-range': [CssProp.PITCH_RANGE],
          position: [CssProp.POSITION],
          quotes: [CssProp.QUOTES],
          resize: [CssProp.RESIZE],
          richness: [CssProp.RICHNESS],
          right: [CssProp.RIGHT],
          speak: [CssProp.SPEAK],
          'speak-header': [CssProp.SPEAK_HEADER],
          'speak-numeral': [CssProp.SPEAK_NUMERAL],
          'speak-punctuation': [CssProp.SPEAK_PUNCTUATION],
          'speech-rate': [CssProp.SPEECH_RATE],
          stress: [CssProp.STRESS],
          'table-layout': [CssProp.TABLE_LAYOUT],
          'text-align': [CssProp.TEXT_ALIGN],
          'text-decoration': [CssProp.TEXT_DECORATION],
          'text-indent': [CssProp.TEXT_INDENT],
          'text-overflow': [CssProp.TEXT_OVERFLOW],
          'text-shadow': [CssProp.TEXT_SHADOW],
          'text-transform': [CssProp.TEXT_TRANSFORM],
          'text-wrap': [CssProp.TEXT_WRAP],
          top: [CssProp.TOP],
          'unicode-bidi': [CssProp.UNICODE_BIDI],
          'vertical-align': [CssProp.VERTICAL_ALIGN],
          visibility: [CssProp.VISIBILITY],
          volume: [CssProp.VOLUME],
          'white-space': [CssProp.WHITE_SPACE],
          width: [CssProp.WIDTH],
          'word-break': [CssProp.WORD_BREAK],
          'word-spacing': [CssProp.WORD_SPACING],
          'word-wrap': [CssProp.WORD_WRAP],
          'z-index': [CssProp.Z_INDEX],
          zoom: [CssProp.ZOOM]
        }
      },
      transformTags: {
        // Set the "rel" attribute for <a> tags to "nofollow".
        a: sanitize_html__WEBPACK_IMPORTED_MODULE_0___default().simpleTransform('a', {
          rel: 'nofollow'
        }),
        // Set the "disabled" attribute for <input> tags.
        input: sanitize_html__WEBPACK_IMPORTED_MODULE_0___default().simpleTransform('input', {
          disabled: 'disabled'
        })
      },
      allowedSchemes: _toConsumableArray((sanitize_html__WEBPACK_IMPORTED_MODULE_0___default().defaults.allowedSchemes)),
      allowedSchemesByTag: {
        // Allow 'attachment:' img src (used for markdown cell attachments).
        img: sanitize_html__WEBPACK_IMPORTED_MODULE_0___default().defaults.allowedSchemes.concat(['attachment'])
      },
      // Override of the default option, so we can skip 'src' attribute validation.
      // 'src' Attributes are validated to be URIs, which does not allow for embedded (image) data.
      // Since embedded data is no longer deemed to be a threat, validation can be skipped.
      // See https://github.com/jupyterlab/jupyterlab/issues/5183
      allowedSchemesAppliedToAttributes: ['href', 'cite']
    };
  }