function writeRuleset(ruleset, filename) {
  const code = `/*
* WARNING: This file is autogenerated using the scripts/generate-rulesets.js
* script. Do not edit manually.
*/

module.exports = Object.freeze(${JSON.stringify({ rules: ruleset }, null, 2)})
`;

  fs.writeFileSync(`./conf/rulesets/solhint-${filename}.js`, code, "utf8");
}